# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-alpine

# Install dependencies
RUN apk add --no-cache build-base libffi-dev openssl-dev

WORKDIR /app
# Copy source
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir mcp httpx python-dotenv

# Expose port if SSE transport is used (default uses stdio)
# EXPOSE 8000

# Default command
CMD ["python", "src/server.py"]
